-- ================================================================
-- SCRIPT DE DESTRUCCIÓN MASIVA: ESQUEMA DB_LOPERS
-- ================================================================

DECLARE @Sql NVARCHAR(MAX) = '';

-- 1. ROMPER TODAS LAS FOREIGN KEYS
SELECT @Sql += 'ALTER TABLE ' + QUOTENAME(TABLE_SCHEMA) + '.' + QUOTENAME(TABLE_NAME) + ' DROP CONSTRAINT ' + QUOTENAME(CONSTRAINT_NAME) + ';' + CHAR(13)
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'DB_LOPERS' AND CONSTRAINT_TYPE = 'FOREIGN KEY';

IF @Sql <> ''
BEGIN
    EXEC sp_executesql @Sql;
    SET @Sql = '';
END

-- 2. BORRAR TODAS LAS TABLAS
SELECT @Sql += 'DROP TABLE ' + QUOTENAME(TABLE_SCHEMA) + '.' + QUOTENAME(TABLE_NAME) + ';' + CHAR(13)
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'DB_LOPERS' AND TABLE_TYPE = 'BASE TABLE';

IF @Sql <> ''
BEGIN
    EXEC sp_executesql @Sql;
    SET @Sql = '';
END

-- 3. BORRAR TODOS LOS STORED PROCEDURES
SELECT @Sql += 'DROP PROCEDURE ' + QUOTENAME(ROUTINE_SCHEMA) + '.' + QUOTENAME(ROUTINE_NAME) + ';' + CHAR(13)
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'DB_LOPERS' AND ROUTINE_TYPE = 'PROCEDURE';

IF @Sql <> ''
BEGIN
    EXEC sp_executesql @Sql;
END

-- 4. FINALMENTE, BORRAR EL ESQUEMA
DROP SCHEMA [DB_LOPERS];
GO

PRINT 'El esquema DB_LOPERS y todo su contenido fueron eliminados con éxito.';
GO